[package]
name = "sanic-core"
description = "Types, configuration, repo matching and trigger logic."
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
color-eyre.workspace = true
globset.workspace = true
indexmap.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
