[package]
name = "sanic-store"
description = "SQLite schema, migrations and queries."
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
color-eyre.workspace = true
rusqlite.workspace = true
sanic-core.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
